server.port=8081
spring.application.name=bff-gateway

# URLs de microservicios
services.kpi.url=${KPI_SERVICE_URL:http://localhost:8084}
services.data.url=${DATA_SERVICE_URL:http://localhost:8083}
services.report.url=${REPORT_SERVICE_URL:http://localhost:8085}

# Logging
logging.level.cl.duoc.cordillera=DEBUG